stages:
  process-data:
    cmd: >
      python ocmscripts/dataset.py
      data/external/2023-clb-multisite.csv
      data/external/2023-isb-multisite.csv
      --output-path=data/processed/dataset.csv
    deps:
      - uv.lock
      - ocmscripts/dataset.py
      - data/external/2023-clb-multisite.csv
      - data/external/2023-isb-multisite.csv
    outs:
      - data/processed/dataset.csv

  sampling:
    cmd: >
      lyscripts sample
      --configs models/configs/simple.ly.yaml
      --configs models/configs/max_llh.ly.yaml
      --configs models/configs/sampling.ly.yaml
      --data.source data/processed/dataset.csv
    deps:
      - uv.lock
      - data/processed/dataset.csv
    params:
      - models/configs/simple.ly.yaml:
      - models/configs/max_llh.ly.yaml:
      - models/configs/sampling.ly.yaml:
    outs:
      - models/histories/simple.csv
      - models/samples/simple.hdf5

  prevalences:
    cmd: >
      lyscripts compute prevalences
      --configs models/configs/simple.ly.yaml
      --configs models/configs/sampling.ly.yaml
      --configs models/configs/scenarios.ly.yaml
      --prevalences.file models/prevalences/simple.hdf5
      --data.source data/processed/dataset.csv
    deps:
      - uv.lock
      - models/samples/simple.hdf5
      - data/processed/dataset.csv
    params:
      - models/configs/simple.ly.yaml:
      - models/configs/sampling.ly.yaml:
      - models/configs/scenarios.ly.yaml:
    outs:
      - models/prevalences/simple.hdf5

  risks:
    cmd: >
      lyscripts compute risks
      --configs models/configs/simple.ly.yaml
      --configs models/configs/sampling.ly.yaml
      --configs models/configs/scenarios.ly.yaml
      --risks.file models/risks/simple.hdf5
    deps:
      - uv.lock
      - models/samples/simple.hdf5
    params:
      - models/configs/simple.ly.yaml:
      - models/configs/sampling.ly.yaml:
      - models/configs/scenarios.ly.yaml:
    outs:
      - models/risks/simple.hdf5
