version: 1

modalities: 
  CT:
    spec: 0.8
    sens: 0.8

scenarios:
  - t_stages: [early]
    mode: HMM
    diagnosis:
      ipsi:
        CT:
          II: healthy
          III: healthy
    involvement:
      ipsi:
        III: involved
  - t_stages: [late]
    mode: HMM
    diagnosis:
      ipsi:
        CT:
          II: involved
          III: healthy
    involvement:
      ipsi:
        III: involved
