version: 1

model:
  class_name: Unilateral
  constructor: binary
  max_time: 10

graph:
  tumor:
    T: [II, III]

  lnl:
    II: [III]
    III: []

distributions: 
  early:
    kind: frozen
    func: binomial
    params: {p: 0.3}
  late:
    kind: parametric
    func: binomial
    params: {p: 0.5}

modalities: 
  max_llh:
    spec: 1.0
    sens: 1.0
    kind: pathological

sampling:
  storage_file: models/samples/simple.hdf5
  history_file: models/histories/simple.csv
  dataset: mcmc
  seed: 42
  walkers_per_dim: 20
  check_interval: 50
  trust_factor: 50
  relative_thresh: 0.05
  thin_by: 50
  num_steps: 100
  inverse_temp: 1
